# -*- coding: utf-8 -*-
"""geoprecio_modelos_ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzLzgAmq4LT1BXKkJ9ODd5VQozcJvkw8

<center> <span style="font-size:16px;">Machine Learning e Inferencia Bayesiana  

UNIVERSIDAD DE GUADALAJARA</span> </center>

<center> <span style="font-size:18px;"><b>Análisis de Precios de Canasta Básica entre tiendas - GEOPRECIO</b></span> </center>  
<center> <span style="font-size:14px;">Carretero Contretas Kitzia D., Cintora Ruvalcaba Samuel S., Hernández Juarez Perla, Molotla Jimenez Isaac E.</span> </center>

---

# Introducción

Aplicamos cinco modelos de *Machine Learning* sobre el dataset **GEOPRECIOS**, que contiene información de precios de productos de la canasta básica en cuatro tiendas: Bodega Aurrera, Walmart, Soriana y La Comer.

Los modelos que se implementarán en orden son:

1. **Regresión múltiple** — predecir el precio unitario de un producto a partir de variables numéricas y codificadas.
2. **Regresión logística** — clasificar si el precio es caro o barato respecto a la mediana.
3. **Árbol de decisión** — clasificar la categoría del producto a partir de sus atributos de precio.
4. **KNN (K Vecinos Más Cercanos)** — clasificar la tienda a partir de características del producto.
5. **Naive Bayes** — clasificar la categoría del producto.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import scipy.stats as st

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (r2_score, mean_squared_error, confusion_matrix, classification_report, accuracy_score, roc_auc_score, ConfusionMatrixDisplay)

url = "https://raw.githubusercontent.com/Perla-Her/proyecto_integrador/refs/heads/main/historial%20base%20de%20datos/geoprecio_ML.csv"
df = pd.read_csv(url)
display(df.head())
print('Dimensiones del dataset:', df.shape)

df.info()

df.isna().any()

"""No hay valores nulos en el dataset, por lo que no es necesario imputar valores faltantes."""

df.describe()

print('Categorías de productos:', df['categoria_ml'].unique())
print('Tiendas:', df['tienda'].unique())
print('Unidades:', df['unit_std'].unique())

df['categoria_ml'].value_counts()

df['tienda'].value_counts()

"""### Valores atípicos"""

plt.figure()
sns.boxplot(x=df['precio_num'], color='steelblue')
plt.xlabel('precio_num')
plt.show()

plt.figure()
sns.boxplot(x=df['cant_std'], color='coral')
plt.xlabel('cant_std')
plt.show()

plt.figure()
sns.boxplot(x=df['precio_unitario'], color='mediumseagreen')
plt.xlabel('precio_unitario')
plt.show()

"""Se observan algunos valores atípicos en `precio_num` y `cant_std`. Revisando el dataset, estos corresponden a presentaciones más grandes de algunos productos (por ejemplo, aceite de 3.5 L), por lo que son válidos y los mantenemos.

### Análisis exploratorio
"""

fig = plt.figure(figsize=(8, 5))
for i, cat in enumerate(df['categoria_ml'].unique()):
    subset = df[df['categoria_ml'] == cat]['precio_unitario']
    plt.hist(subset, alpha=0.6, label=cat, bins=15)
plt.xlabel('Precio unitario')
plt.ylabel('Frecuencia')
plt.title('Distribución de precio unitario por categoría')
plt.legend()
plt.show()

df.groupby('tienda')['precio_unitario'].mean().plot(kind='bar', color=['steelblue','coral','mediumseagreen','mediumpurple'])
plt.title('Precio unitario promedio por tienda')
plt.xlabel('Tienda')
plt.ylabel('Precio unitario promedio')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

num_cols = ['precio_num', 'cant_std', 'precio_unitario']
sns.heatmap(df[num_cols].corr(), cmap='YlGnBu', annot=True)
plt.title('Matriz de correlación')
plt.show()

"""Se observa una correlación muy alta (0.93) entre `precio_num` y `cant_std`, lo que tiene sentido: a mayor cantidad, mayor precio total. El `precio_unitario` tiene una correlación baja con las otras variables, lo que lo hace una variable objetivo más interesante para modelar.

### Preparación de variables codificadas

Para los modelos necesitamos convertir las variables categóricas a numéricas.
"""

df_model = df[['precio_num', 'cant_std', 'precio_unitario', 'tienda', 'categoria_ml', 'unit_std']].copy()

df_dummies = pd.get_dummies(df_model[['tienda', 'unit_std']], dtype=int)
df_model = pd.concat([df_model, df_dummies], axis=1)
df_model = df_model.drop(['tienda', 'unit_std'], axis=1)

display(df_model.head())
print('Shape:', df_model.shape)

"""---

# 1. Regresión Múltiple

El objetivo es **predecir el precio unitario** (`precio_unitario`) a partir de las demás variables numéricas y las variables categóricas codificadas. La regresión lineal múltiple tiene la forma:

$$\hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \ldots + \beta_n x_n$$
"""

feature_cols_reg = [c for c in df_model.columns if c not in ['precio_unitario', 'categoria_ml']]
X_reg = df_model[feature_cols_reg]
y_reg = df_model['precio_unitario']

print('Variables predictoras:', feature_cols_reg)

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.3, random_state=1)

reg = LinearRegression()
reg.fit(X_train_r, y_train_r)

y_pred_r = reg.predict(X_test_r)

R2 = r2_score(y_test_r, y_pred_r)
MSE = mean_squared_error(y_test_r, y_pred_r)
RMSE = np.sqrt(MSE)
p_vars = X_reg.shape[1]
SSD = np.sum((y_pred_r - y_test_r)**2)
RSE = np.sqrt(SSD / (len(y_test_r) - 1 - p_vars))

print('R2:  ', round(R2, 4))
print('MSE: ', round(MSE, 4))
print('RMSE:', round(RMSE, 4))
print('RSE: ', round(RSE, 4))
print('RSE porcentual: ', round(RSE / y_test_r.mean(), 4), '%')

coef_df = pd.DataFrame({'Variable': feature_cols_reg, 'Coeficiente': reg.coef_})
coef_df = coef_df.sort_values('Coeficiente', ascending=False)
display(coef_df)
print('Intercepto:', round(reg.intercept_, 4))

plt.scatter(y_test_r, y_pred_r, color='steelblue', alpha=0.6)
plt.plot([y_test_r.min(), y_test_r.max()], [y_test_r.min(), y_test_r.max()], '--r')
plt.xlabel('Precio unitario real')
plt.ylabel('Precio unitario predicho')
plt.title('Regresión múltiple: Real vs Predicho')
plt.show()

"""## Residuos"""

residuos = y_pred_r - y_test_r

plt.hist(residuos, bins=20, color='steelblue', edgecolor='white')
plt.xlabel('Residuo')
plt.ylabel('Frecuencia')
plt.title('Histograma de residuos')
plt.show()

st.probplot(residuos, dist='norm', plot=plt)
plt.title('Q-Q plot de residuos')
plt.show()

"""## Shapiro-Wilk

"""

significance = 0.05
standardized = st.zscore(residuos)
stat, p = st.shapiro(standardized)
print('Prueba de Shapiro-Wilk')
print('estadístico W=%.3f, p-valor=%.3f' % (stat, p))
if p > significance:
    print('Probablemente es gaussiano')
else:
    print('Probablemente no es gaussiano')

n = len(X_train_r)
p_vars = X_reg.shape[1]
SSD = np.sum(residuos**2)
RSE = np.sqrt(SSD / (len(y_test_r) - 1 - p_vars))
print('RSE: ', round(RSE, 4))
print('RSE porcentual: ', round(RSE / y_test_r.mean(), 4), '%')

"""### Interpretación — Regresión múltiple

El modelo de regresión múltiple obtiene un $R^2$ que indica qué tan bien las variables predictoras explican la variación en el precio unitario. Un error residual porcentual moderado sugiere que hay variabilidad en los precios que no se captura completamente con las variables disponibles. Los coeficientes de las variables dummy de tienda muestran diferencias de precio entre establecimientos. Los residuos presentan una distribución aproximadamente normal, lo que valida el uso de regresión lineal en este caso.

---

# 2. Regresión Logística

Para este modelo creamos una variable objetivo binaria: si el precio unitario de un producto es **mayor a la mediana** se clasifica como `caro` (1), de lo contrario como `barato` (0). El objetivo es predecir esta etiqueta a partir de las demás características.
"""

mediana_precio = df['precio_unitario'].median()
print('Mediana del precio unitario:', mediana_precio)

df_log = df_model.copy()
df_log['precio_caro'] = (df_log['precio_unitario'] > mediana_precio).astype(int)
df_log['precio_caro'].value_counts()

df_log['precio_caro'].value_counts().plot(kind='bar', color=['steelblue', 'coral'])
plt.title('Distribución de la variable objetivo (caro/barato)')
plt.xlabel('Precio caro (1) / Precio barato (0)')
plt.ylabel('Frecuencia')
plt.xticks(rotation=0)
plt.show()

feature_cols_log = [c for c in df_log.columns if c not in ['precio_unitario', 'precio_caro', 'categoria_ml']]
X_log = df_log[feature_cols_log]
y_log = df_log['precio_caro']

print('Variables predictoras:', feature_cols_log)

X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X_log, y_log, test_size=0.3, random_state=1)

log_model = LogisticRegression(max_iter=500, random_state=1)
log_model.fit(X_train_l, y_train_l)

y_pred_l = log_model.predict(X_test_l)
y_prob_l = log_model.predict_proba(X_test_l)[:, 1]

accuracy_l = accuracy_score(y_test_l, y_pred_l)
auc_l = roc_auc_score(y_test_l, y_prob_l)

print(f'Accuracy: {accuracy_l:.4f}')
print(f'AUC:      {auc_l:.4f}')
print()
print('Reporte de clasificación')
print(classification_report(y_test_l, y_pred_l))

"""## Matriz de confusión"""

cm_l = confusion_matrix(y_test_l, y_pred_l)
disp_l = ConfusionMatrixDisplay(confusion_matrix=cm_l, display_labels=['Barato', 'Caro'])
disp_l.plot(cmap='Blues')
plt.title('Matriz de confusión — Regresión Logística')
plt.show()

from sklearn.metrics import roc_curve
fpr_l, tpr_l, _ = roc_curve(y_test_l, y_prob_l)
plt.plot(fpr_l, tpr_l, color='steelblue', label=f'ROC (AUC = {auc_l:.3f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.title('Curva ROC — Regresión Logística')
plt.legend()
plt.show()

coef_log = pd.DataFrame({'Variable': feature_cols_log, 'Coeficiente': log_model.coef_[0]})
coef_log = coef_log.sort_values('Coeficiente', ascending=False)
display(coef_log)

"""## Validación cruzada"""

cv_scores_l = cross_val_score(log_model, X_log, y_log, cv=5)
print('Accuracy por fold:', cv_scores_l)
print('Accuracy promedio (CV):', round(cv_scores_l.mean(), 4))

"""### Interpretación — Regresión Logística

El modelo de regresión logística clasifica si el precio de un producto es caro o barato respecto a la mediana. La variable `precio_num` y `cant_std` tienen el mayor peso en la decisión del modelo. El accuracy y el AUC indican un buen desempeño del clasificador. La curva ROC se aleja de la diagonal, lo que confirma que el modelo es útil. La validación cruzada muestra resultados consistentes entre folds, lo que sugiere que el modelo generaliza bien.

---

# 3. Árbol de Decisión

El árbol de decisión se usará para **clasificar la categoría del producto** (`categoria_ml`: Aceite, Leche, Frijol, Pasta) a partir de sus atributos de precio. Este modelo genera reglas de decisión interpretables.
"""

le = LabelEncoder()
df_tree = df_model.copy()
df_tree['categoria_cod'] = le.fit_transform(df['categoria_ml'])

print('Codificación de categorías:')
for i, c in enumerate(le.classes_):
    print(f'  {c} -> {i}')

feature_cols_tree = [c for c in df_tree.columns if c not in ['categoria_ml', 'categoria_cod']]
X_tree = df_tree[feature_cols_tree]
y_tree = df_tree['categoria_cod']

print('Variables predictoras:', feature_cols_tree)

plt.hist(df['categoria_ml'], color='steelblue', edgecolor='white')
plt.xlabel('Categoría')
plt.ylabel('Count')
plt.title('Distribución de categorías')
plt.show()

X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(X_tree, y_tree, test_size=0.3, random_state=1)

tree = DecisionTreeClassifier(criterion='entropy', min_samples_split=10, min_samples_leaf=3, random_state=1)
tree.fit(X_train_t, y_train_t)

y_pred_t = tree.predict(X_test_t)
y_prob_t = tree.predict_proba(X_test_t)

accuracy_t = accuracy_score(y_test_t, y_pred_t)
auc_t = roc_auc_score(y_test_t, y_prob_t, multi_class='ovr')

print(f'Accuracy: {accuracy_t:.4f}')
print(f'AUC:      {auc_t:.4f}')
print()
print('Reporte de clasificación')
print(classification_report(y_test_t, y_pred_t, target_names=le.classes_))

cm_t = confusion_matrix(y_test_t, y_pred_t)
disp_t = ConfusionMatrixDisplay(confusion_matrix=cm_t, display_labels=le.classes_)
disp_t.plot(cmap='Blues')
plt.title('Matriz de confusión — Árbol de Decisión')
plt.show()

feat_imp = pd.DataFrame({'Variable': feature_cols_tree, 'Importancia': tree.feature_importances_})
feat_imp = feat_imp[feat_imp['Importancia'] > 0].sort_values('Importancia', ascending=False)
feat_imp.plot(kind='bar', x='Variable', y='Importancia', color='steelblue', legend=False)
plt.title('Importancia de variables — Árbol de Decisión')
plt.xlabel('Variable')
plt.ylabel('Importancia')
plt.tight_layout()
plt.xticks(rotation=30)
plt.show()

from sklearn.metrics import roc_curve
from sklearn.preprocessing import label_binarize

y_test_bin = label_binarize(y_test_t, classes=[0, 1, 2, 3])
n_classes = y_test_bin.shape[1]

plt.figure(figsize=(8, 6))
colors = ['steelblue', 'coral', 'mediumseagreen', 'mediumpurple']
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_t[:, i])
    plt.plot(fpr, tpr, color=colors[i], label=le.classes_[i])

plt.plot([0, 1], [0, 1], 'k--')
plt.title('Curvas ROC por clase (One-vs-Rest) — Árbol de Decisión')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.legend()
plt.show()

"""## Validación Cruzada"""

cv_scores_t = cross_val_score(tree, X_tree, y_tree, cv=5)
print('Accuracy por fold:', cv_scores_t)
print('Accuracy promedio (CV):', round(cv_scores_t.mean(), 4))

"""### Interpretación — Árbol de Decisión

El árbol de decisión clasifica correctamente la categoría del producto con buen desempeño. Las variables `precio_unitario` y `precio_num` son las más importantes para distinguir entre categorías, lo cual es esperado ya que cada tipo de producto tiene rangos de precio distintos. La curva ROC por clase muestra que el modelo diferencia bien especialmente la categoría Aceite y Leche. La validación cruzada muestra resultados consistentes.

---

# 4. KNN (K Vecinos Más Cercanos)

Usamos el modelo KNN para **clasificar la categoría del producto** (`categoria_ml`). Dado que KNN es sensible a la escala de las variables, primero estandarizamos los datos.
"""

X_knn = df_tree[feature_cols_tree].copy()
y_knn = df_tree['categoria_cod'].copy()

scaler = StandardScaler()
X_knn_std = scaler.fit_transform(X_knn)
X_knn_std = pd.DataFrame(X_knn_std, columns=X_knn.columns)
X_knn_std.head()

X_train_k, X_test_k, y_train_k, y_test_k = train_test_split(X_knn_std, y_knn, test_size=0.3, random_state=1, stratify=y_knn)

accuracies = []
k_values = range(1, 21)

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_k, y_train_k)
    acc = accuracy_score(y_test_k, knn.predict(X_test_k))
    accuracies.append(acc)

plt.plot(k_values, accuracies, marker='o', color='steelblue')
plt.xlabel('K')
plt.ylabel('Accuracy')
plt.title('Accuracy vs K — KNN')
plt.show()

best_k = k_values[np.argmax(accuracies)]
print('Mejor K:', best_k, '  Accuracy:', round(max(accuracies), 4))

knn_model = KNeighborsClassifier(n_neighbors=best_k)
knn_model.fit(X_train_k, y_train_k)

y_pred_k = knn_model.predict(X_test_k)
y_prob_k = knn_model.predict_proba(X_test_k)

accuracy_k = accuracy_score(y_test_k, y_pred_k)
auc_k = roc_auc_score(y_test_k, y_prob_k, multi_class='ovr')

print(f'Accuracy: {accuracy_k:.4f}')
print(f'AUC:      {auc_k:.4f}')
print()
print('Reporte de clasificación')
print(classification_report(y_test_k, y_pred_k, target_names=le.classes_))

cm_k = confusion_matrix(y_test_k, y_pred_k)
disp_k = ConfusionMatrixDisplay(confusion_matrix=cm_k, display_labels=le.classes_)
disp_k.plot(cmap='Blues')
plt.title('Matriz de confusión — KNN')
plt.show()

y_test_bin_k = label_binarize(y_test_k, classes=[0, 1, 2, 3])

plt.figure(figsize=(8, 6))
for i in range(4):
    fpr, tpr, _ = roc_curve(y_test_bin_k[:, i], y_prob_k[:, i])
    plt.plot(fpr, tpr, color=colors[i], label=le.classes_[i])

plt.plot([0, 1], [0, 1], 'k--')
plt.title('Curvas ROC por clase (One-vs-Rest) — KNN')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.legend()
plt.show()

"""## Validación Cruzada"""

cv_scores_k = cross_val_score(knn_model, X_knn_std, y_knn, cv=5)
print('Accuracy por fold:', cv_scores_k)
print('Accuracy promedio (CV):', round(cv_scores_k.mean(), 4))

"""### Interpretación — KNN

El modelo KNN clasifica la categoría del producto mediante proximidad entre observaciones. La búsqueda del mejor K muestra que el modelo mejora conforme aumenta K hasta cierto punto, donde empieza a perder información local. La estandarización fue fundamental para que todas las variables contribuyeran de igual forma al cálculo de distancias. El accuracy obtenido y el AUC muestran que KNN tiene un desempeño competitivo en este dataset.

---

# 5. Naive Bayes

Aplicamos el clasificador **Naive Bayes Gaussiano** para clasificar la categoría del producto. Este modelo asume que las variables son independientes entre sí y que siguen una distribución normal, lo que lo hace computacionalmente eficiente.
"""

X_nb = df[['precio_num', 'cant_std', 'precio_unitario']].copy()
y_nb = le.transform(df['categoria_ml'])

print('Shape:', X_nb.shape)
display(X_nb.head())

df_nb_exp = X_nb.copy()
df_nb_exp['categoria'] = df['categoria_ml'].values
df_nb_exp.groupby('categoria').mean()

X_train_nb, X_test_nb, y_train_nb, y_test_nb = train_test_split(X_nb, y_nb, test_size=0.3, random_state=1, stratify=y_nb)

nb_model = GaussianNB()
nb_model.fit(X_train_nb, y_train_nb)

y_pred_nb = nb_model.predict(X_test_nb)
y_prob_nb = nb_model.predict_proba(X_test_nb)

accuracy_nb = accuracy_score(y_test_nb, y_pred_nb)
auc_nb = roc_auc_score(y_test_nb, y_prob_nb, multi_class='ovr')

print(f'Accuracy: {accuracy_nb:.4f}')
print(f'AUC:      {auc_nb:.4f}')
print()
print('Reporte de clasificación')
print(classification_report(y_test_nb, y_pred_nb, target_names=le.classes_))

cm_nb = confusion_matrix(y_test_nb, y_pred_nb)
disp_nb = ConfusionMatrixDisplay(confusion_matrix=cm_nb, display_labels=le.classes_)
disp_nb.plot(cmap='Blues')
plt.title('Matriz de confusión — Naive Bayes')
plt.show()

y_test_bin_nb = label_binarize(y_test_nb, classes=[0, 1, 2, 3])

plt.figure(figsize=(8, 6))
for i in range(4):
    fpr, tpr, _ = roc_curve(y_test_bin_nb[:, i], y_prob_nb[:, i])
    plt.plot(fpr, tpr, color=colors[i], label=le.classes_[i])

plt.plot([0, 1], [0, 1], 'k--')
plt.title('Curvas ROC por clase (One-vs-Rest) — Naive Bayes')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.legend()
plt.show()

"""## Validación Cruzada"""

cv_scores_nb = cross_val_score(nb_model, X_nb, y_nb, cv=5)
print('Accuracy por fold:', cv_scores_nb)
print('Accuracy promedio (CV):', round(cv_scores_nb.mean(), 4))

"""### Interpretación — Naive Bayes

El clasificador Naive Bayes Gaussiano asume independencia entre las variables y distribución normal. A pesar de ser un modelo muy simple, logra un desempeño razonable. Dado que los precios de cada categoría tienen distribuciones distintas, el modelo puede separar bastante bien las clases usando solo tres variables numéricas. La validación cruzada confirma la estabilidad del modelo.

---

# Comparativa de modelos
"""

resultados = pd.DataFrame({
    'Modelo': ['Regresión Múltiple', 'Regresión Logística', 'Árbol de Decisión', 'KNN', 'Naive Bayes'],
    'Tarea': ['Regresión', 'Clasificación binaria', 'Clasificación multiclase', 'Clasificación multiclase', 'Clasificación multiclase'],
    'Métrica principal': ['R2', 'Accuracy', 'Accuracy', 'Accuracy', 'Accuracy'],
    'Valor': [
        round(R2, 4),
        round(accuracy_l, 4),
        round(accuracy_t, 4),
        round(accuracy_k, 4),
        round(accuracy_nb, 4)
    ],
    'AUC': [
        '-',
        round(auc_l, 4),
        round(auc_t, 4),
        round(auc_k, 4),
        round(auc_nb, 4)
    ],
    'CV promedio': [
        '-',
        round(cv_scores_l.mean(), 4),
        round(cv_scores_t.mean(), 4),
        round(cv_scores_k.mean(), 4),
        round(cv_scores_nb.mean(), 4)
    ]
})

display(resultados)

modelos_clf = ['Reg. Logística', 'Árbol de Decisión', 'KNN', 'Naive Bayes']
acc_valores = [accuracy_l, accuracy_t, accuracy_k, accuracy_nb]
colores_bar = ['steelblue', 'coral', 'mediumseagreen', 'mediumpurple']

plt.bar(modelos_clf, acc_valores, color=colores_bar, edgecolor='white')
plt.ylim(0, 1.05)
plt.ylabel('Accuracy')
plt.title('Comparativa de Accuracy — Modelos de clasificación')
for i, v in enumerate(acc_valores):
    plt.text(i, v + 0.01, str(round(v, 3)), ha='center')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

auc_valores = [auc_l, auc_t, auc_k, auc_nb]

plt.bar(modelos_clf, auc_valores, color=colores_bar, edgecolor='white')
plt.ylim(0, 1.05)
plt.ylabel('AUC')
plt.title('Comparativa de AUC — Modelos de clasificación')
for i, v in enumerate(auc_valores):
    plt.text(i, v + 0.01, str(round(v, 3)), ha='center')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

cv_valores = [cv_scores_l.mean(), cv_scores_t.mean(), cv_scores_k.mean(), cv_scores_nb.mean()]

plt.bar(modelos_clf, cv_valores, color=colores_bar, edgecolor='white')
plt.ylim(0, 1.05)
plt.ylabel('Accuracy (CV 5-fold)')
plt.title('Comparativa de Validación Cruzada — Modelos de clasificación')
for i, v in enumerate(cv_valores):
    plt.text(i, v + 0.01, str(round(v, 3)), ha='center')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""### Conclusiones generales

**Regresión múltiple**: el modelo predice el precio unitario con un $R^2$ que refleja la dificultad de estimar precios exactos solamente a partir de atributos básicos del producto. El RMSE indica el error promedio en pesos. Es un modelo útil como referencia para entender qué variables influyen más en el precio.

**Regresión logística**: al convertir el problema a clasificación binaria (caro/barato), el modelo logra un buen accuracy y AUC. Es el modelo más fácil de interpretar en términos de coeficientes y dirección de las variables.

**Árbol de decisión**: obtiene un accuracy alto clasificando las cuatro categorías de productos. La variable más importante es el precio unitario, lo cual es intuitivo ya que cada categoría tiene rangos de precio distintos. El árbol genera reglas interpretables, lo que lo hace muy valioso para explicar las decisiones.

**KNN**: con el K óptimo encontrado, obtiene resultados comparables al árbol de decisión. Requiere estandarización de variables y es más costoso computacionalmente, pero funciona bien en este dataset relativamente pequeño.

**Naive Bayes**: a pesar de ser el modelo más simple, tiene un desempeño razonable usando solo tres variables numéricas. Demuestra que cuando las distribuciones de precio por categoría son suficientemente distintas, incluso un modelo con supuestos fuertes puede clasificar bien.

**Mejor(es) modelo(s)**: el **Árbol de Decisión** y **KNN** son los modelos con mejor desempeño en la tarea de clasificación multiclase, tanto en accuracy como en AUC y validación cruzada. El Árbol de Decisión tiene la ventaja adicional de ser interpretable: se puede ver exactamente qué regla de precio determina la categoría del producto. Para la tarea de regresión, el modelo funciona razonablemente considerando la naturaleza del dataset.
"""

