# -*- coding: utf-8 -*-
"""Razonentrevarianzas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbU7VWUrVi1nWdfMcThn2i1U-wLOsm5V
"""

import pandas as pd
import numpy as np
from scipy import integrate
import scipy.special as special
from scipy.stats import norm
import itertools
url = "https://raw.githubusercontent.com/Perla-Her/proyecto_integrador/refs/heads/main/historial%20base%20de%20datos/geoprecio_clean.csv"
df = pd.read_csv(url)

#Filtro
def filtro_arroz_avanzado(nombre):
    n = str(nombre).lower()
    if 'arroz' not in n: return False
    prohibidos = ['pan', 'sazonador','inflado','harina', 'atun', 'atún','licor', 'galleta', 'cereal', 'vinagre','fideo','yogur','noodle','tostadas','liquido','papel','sticks','huevos','sustituto','italriso']
    return not any(p in n for p in prohibidos)
df_a = df[
    (df['nombre'].apply(filtro_arroz_avanzado))
].copy()
df_a = df_a[(df_a['precio_unitario'] >= 10) & (df_a['precio_unitario'] <= 80)].copy()

#Prueba de bondad del ajuste(Shapiro-Wilk)

def shapiro_wilk_manual(data):
    """
    Calcula el estadístico W y su p-valor basado en el algoritmo de
    transformación normal de Royston (1992).
    """
    x = np.sort(data)
    n = len(x)

    if n < 3:
        return None, None

    # 1. Estadístico W
    m = norm.ppf((np.arange(1, n + 1) - 0.375) / (n + 0.25))
    a = m / np.sqrt(np.sum(m**2))

    den = np.sum((x - np.mean(x))**2)
    if den == 0:
        return 1.0, 1.0

    w = (np.sum(a * x)**2) / den

    w = min(w, 0.999999999)

    # 2. Aproximación del p-valor
    if n == 3:
        # Fórmula para n = 3
        w = max(0.75, w)
        p_val = (6 / np.pi) * (np.arcsin(np.sqrt(w)) - np.arcsin(np.sqrt(0.75)))

    elif n <= 11:
        # Aproximación polinómica para muestras muy pequeñas (4 <= n <= 11)
        gamma = 0.459 * n - 2.273
        y = -np.log(gamma - np.log(1 - w))

        mu = -0.0006714 * (gamma**3) + 0.025054 * (gamma**2) - 0.39978 * gamma + 0.5440
        sigma = np.exp(-0.0020322 * (n**3) + 0.062767 * (n**2) - 0.77857 * n + 1.3822)

        z = (y - mu) / sigma
        p_val = 1 - norm.cdf(z)

    else:
        # Aproximación para muestras grandes (n >= 12)
        y = np.log(1 - w)
        nl = np.log(n)

        # Polinomios cúbicos correctos para la normalizacion
        mu = 0.0038915 * (nl**3) - 0.083751 * (nl**2) - 0.31082 * nl - 1.5861
        sigma = np.exp(0.0030302 * (nl**2) - 0.082676 * nl - 0.4803)

        z = (y - mu) / sigma
        p_val = 1 - norm.cdf(z)

    return w, p_val

results_shapiro = []

for tienda, group in df_a.groupby('tienda'):
    data = group['precio_unitario'].dropna().values

    if len(data) >= 3:
        w_manual, p_manual = shapiro_wilk_manual(data)
        results_shapiro.append({
            'Tienda': tienda,
            'W_Manual': w_manual,
            'p-valor': p_manual,
            'Normalidad': 'Sí' if p_manual > 0.05 else 'No'
        })
    else:
        results_shapiro.append({
            'Tienda': tienda,
            'W_Manual': None,
            'p-valor': None,
            'Normalidad': 'Datos insuficientes'
        })

shapiro_manual_df = pd.DataFrame(results_shapiro)
display(shapiro_manual_df)

#Razon entre varianzas
def fdist(f_val, df1, df2):
    if f_val <= 0: return 0.0
    num = special.gamma((df1 + df2) / 2.0) * ((df1 / df2)**(df1 / 2.0)) * (f_val**((df1 / 2.0) - 1.0))
    den = special.gamma(df1 / 2.0) * special.gamma(df2 / 2.0) * ((1.0 + (df1 * f_val) / df2)**((df1 + df2) / 2.0))
    return num / den

tiendas = [t for t in df_a['tienda'].unique() if t.lower() != 'la comer']
combinaciones = list(itertools.combinations(tiendas, 2))

print(f"Análisis de Varianzas")
print(f"{'Comparación':<40} | {'F Calc':<8} | {'F Crit':<8} | {'Resultado'}")
print("-" * 85)

for t1, t2 in combinaciones:
    d1 = df_a[df_a['tienda'] == t1]['precio_unitario'].dropna()
    d2 = df_a[df_a['tienda'] == t2]['precio_unitario'].dropna()

    v1, v2 = len(d1) - 1, len(d2) - 1
    s1_sq, s2_sq = d1.var(), d2.var()

    if s1_sq >= s2_sq:
        f_calc = s1_sq / s2_sq
        df_n, df_d = v1, v2
    else:
        f_calc = s2_sq / s1_sq
        df_n, df_d = v2, v1

    area_objetivo = 0.025 # alpha/2 para test de dos colas, f_calc >= 1
    f_critico = 0
    f_espacio_local = np.linspace(0.01, 20, 2000)

    for f_v in f_espacio_local:
        # Integracion de f_v al infinito
        p, _ = integrate.quad(fdist, f_v, np.inf, args=(df_n, df_d))
        if p <= area_objetivo:
            f_critico = f_v
            break

    res = "Rechaza H0" if f_calc > f_critico else "No Rechaza"

    print(f"{t1 + ' vs ' + t2:<40} | {f_calc:<8.4f} | {f_critico:<8.3f} | {res}")

#Prueba de levene con todas las tiendas
# 1. Datos transformados (Z_ij = |Y_ij - mediana_i|)

tiendas_completas = df_a['tienda'].unique()
grupos_precios = [df_a[df_a['tienda'] == t]['precio_unitario'].values for t in tiendas_completas]
transformados = [np.abs(g - np.median(g)) for g in grupos_precios]

# 2. Estadístico F de Levene
k = len(tiendas_completas) #
N = sum(len(g) for g in transformados)

# Medias de las desviaciones por grupo y media global de desviaciones
medias_grupos = [np.mean(g) for g in transformados]
media_global = np.mean(np.concatenate(transformados))

# Suma de cuadrados entre grupos (Numerador)
ss_entre = sum(len(g) * (medias_grupos[i] - media_global)**2 for i, g in enumerate(transformados))
# Suma de cuadrados dentro de los grupos (Denominador)
ss_dentro = sum(sum((x - medias_grupos[i])**2 for x in g) for i, g in enumerate(transformados))

df_n_lev = k - 1
df_d_lev = N - k

f_levene_calc = (ss_entre / df_n_lev) / (ss_dentro / df_d_lev)

# 3. Valor crítico (Alpha = 0.05, Cola derecha)
area_objetivo = 0.05
f_crit_lev = 0
for f_v in np.linspace(0.01, 20, 5000):
    p, _ = integrate.quad(fdist, f_v, 100, args=(df_n_lev, df_d_lev))
    if p <= area_objetivo:
        f_crit_lev = f_v
        break

print(f"Análisis de Levene con todas las tiendas")
print(f"Estadístico F de Levene calculado: {f_levene_calc:.4f}")
print(f"Valor crítico F ({df_n_lev}, {df_d_lev}): {f_crit_lev:.3f}")

if f_levene_calc > f_crit_lev:
    print("Resultado: Se rechaza H0. Las varianzas no son homogéneas (Heterocedasticidad).")
else:
    print("Resultado: No se rechaza H0. Las varianzas son homogéneas (Homocedasticidad).")